name: PR Title Check
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run PR title check
        run: |
          if [ "${{ github.event.action }}" == "synchronize" ] && [ -z "${{ github.event.changes.title }}" ]; then
            echo "No PR title changes."
            exit 0
          else
            node .github/scripts/pr-title-check.js
          fi
